name: Rust Code Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Clippy
      run: rustup component add clippy rustfmt
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Rustfmt
      run: cargo fmt --all -- --check
