name: Rust Code Check

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
  # push:
  #   branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # NOTE: The cache will only be saved if the whole job succeeds!
    - name: Cache OpenCV
      id: opencv-cache
      uses: actions/cache@v3
      with:
        path: ./opencv-install
        key: ${{ runner.os }}-opencv-cache

    - name: Install OpenCV
      uses: rayandrews/with-opencv-action@v1
      with:
        dir: ./opencv-install
        cached: ${{ steps.opencv-cache.outputs.cache-hit }}
        opencv-version: '4.6.0'
        WITH_QT: ON

    - name: Install Clippy and Rustfmt
      run: rustup component add clippy rustfmt

    - name: Run Clippy
      run: cargo clippy -- -D warnings

    - name: Run Rustfmt
      run: cargo fmt --all -- --check

    - name: Build Artifact
      run: cargo build --release

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: mtfg-rs_x86_64
        path: ./target/release/mtfg-rs
